print('Welcom to "SAU"',end='')
print("Welcom to 'DTI'",end="")
print("---------------")
print('Welcome to \SAU\'')
print("Welcom to\"DTI\"")
print("_ _ _ _ _ _ _ _ _")
print(4546)
print(4547.0545)
print(True)
print(False)
print(15 * 10 + 2 )# expression นิจพน์
print(True or False and False)